---
  - name: Activity1 Playbook
    hosts: webservers
    become: true
    tasks:
    
    - name: Install docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Install docker-container
      docker_container:
        name: dvwa
        state: present
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
